pipeline {
    agent any
    stages {
        stage('checkout') {
            steps{
             git branch: 'main', url: 'https://github.com/bouchrasource/pj_jenk.git'
            }  

            }
        
        stage('clean'){
            steps{
                dir ('trading'){
               bat './mvnw clean' 
              
    }
                
            }
    }
    stage('compile'){
            steps{
                dir ('trading'){
             
               bat './mvnw compile'
               
    }
                
            }
    }
    stage('test'){
            steps{
                dir ('trading'){
               
               bat './mvnw test'
               
    }
                
            }
}

  stage('sonar'){
            steps{
                dir ('trading'){

               bat './mvnw clean verify sonar:sonar -Dsonar.projectKey=pj_jenk -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_3da8c7a55b9011cbc23d9104e4b34c0af033dc59'

    }

            }
    }
    stage('package'){
            steps{
                dir ('trading'){
              
               bat './mvnw package'
              
    }
                
            }
    }
    stage('archive'){
            steps{
                dir ('trading'){
              
               bat 'rename target\\trading-0.0.1-SNAPSHOT.jar trading-%BUILD_NUMBER%.jar'
               archiveArtifacts artifacts: 'target\\trading-*.jar', followSymlinks: false
    }
                
            }
    }
    
}
}
